
-- Вставить данные в таблицу groups
INSERT INTO groups ("group") VALUES
                                 ('test'),
                                 ('three days grace'),
                                 ('123123');

-- Вставить данные в таблицу songs
INSERT INTO songs (group_id, song, text, release_date, link) VALUES
                                                                 ((SELECT id FROM groups WHERE "group" = 'test'), 'test', 'test test test test', '12.09.2005', 'http://qwertty.test'),
                                                                 ((SELECT id FROM groups WHERE "group" = 'three days grace'), 'Give me a reason', '[Intro]\nOh, oh, oh\n\n[Verse 1]\nFeed on me\nYou know I’m never far\nFeed off me\nLike a vulture on a deer hit by a car\nI can only do so much\nAnd of course it’s never enough\nI don’t think that you see\nExactly what you’re doing to me\nDon’t speak\nDon''t speak\n\n[Chorus]\nGive me a reason to turn and run\nGive me a reason to burn this house down\nGive me a reason\nI wish you would\nI wish you would\nWish you would\nGive me a reason for disaster\nAnd I’ll be happy ever after\nGive me a reason\nI wish you would\nI wish you would\nWish you would\nYou might also like\nSlim Pickins\nSabrina Carpenter\nSomeone Who Cares\nThree Days Grace\nMisery Loves My Company\nThree Days Grace\n\n[Verse 2]\nSo you''ve tried your best\nTo get out of this mess\nBut that’s just a joke\nYou’ve never awoke\nTo the sound of a mother screaming at night\nDon’t speak\nDon''t speak\n\n[Chorus]\nGive me a reason to turn and run\nGive me a reason to burn this house down\nGive me a reason\nI wish you would\nI wish you would\nWish you would\nGive me a reason for disaster\nAnd I’ll be happy ever after\nGive me a reason\nI wish you would\nI wish you would\nWish you would\n\n[Bridge]\nI wish you would\nWish you would\nWish you would\nWish you would\nWish you would\n\n[Chorus]\nGive me a reason to turn and run\nGive me a reason to burn this house down\nGive me a reason\nI wish you would\nI wish you would\nWish you would\nGive me a reason for disaster\nAnd I’ll be happy ever after\nGive me a reason to turn and run\nI wish you would\nI wish you would', '16.12.2004', 'http://qwertty.test'),
                                                                 ((SELECT id FROM groups WHERE "group" = '123123'), '123123', '1231321', '07.08.2019', 'http://qwertty.test');
